# Generated by Django 5.2.6 on 2025-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birth_of_date",
            new_name="date_of_birth",
        ),
    ]
