# Generated by Django 5.2.6 on 2025-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_birth_of_date_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=225),
        ),
    ]
