# Generated by Django 5.2.5 on 2025-09-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desciption",
            new_name="description",
        ),
    ]
