# Generated by Django 5.2.5 on 2025-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to="api.product"
            ),
        ),
    ]
